server:
  port: 7070
logging:
  level:
    com.elder.scrabble: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
